apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.crud.name }}
  labels:
    app: {{ .Values.crud.name }}
    group: {{ .Values.crud.group }}
spec:
  replicas: {{ .Values.crud.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.crud.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.crud.name }}
        group: {{ .Values.crud.group }}
    spec:
      containers:
        - name: {{ .Values.crud.name }}
          image: {{ .Values.crud.container.image }}:{{ .Values.crud.container.tag }}
          imagePullPolicy: {{ .Values.crud.container.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.crud.container.port }}
          envFrom:
            {{- range .Values.crud.container.config }}
            - configMapRef:
                name: {{ .name }}
            {{- end}}
          env:
            {{- range .Values.crud.container.env}}
            - name: {{ .name}}
              value: {{ .value}}
            {{- end}}